saleor/dashboard/menu/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.menu_list, name="menu-list"),
    url(r"^add/$", views.menu_create, name="menu-add"),
    url(r"^(?P<pk>[0-9]+)/edit/$", views.menu_edit, name="menu-edit"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.menu_delete, name="menu-delete"),
    url(r"^(?P<pk>[0-9]+)/$", views.menu_details, name="menu-details"),
    url(r"^(?P<menu_pk>[0-9]+)/add/$", views.menu_item_create, name="menu-item-add"),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/add/$",
        views.menu_item_create,
        name="menu-item-add",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/edit/$",
        views.menu_item_edit,
        name="menu-item-edit",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/delete/$",
        views.menu_item_delete,
        name="menu-item-delete",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/$",
        views.menu_item_details,
        name="menu-item-details",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/items/reorder/$",
        views.ajax_reorder_menu_items,
        name="menu-items-reorder",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/items/reorder/$",
        views.ajax_reorder_menu_items,
        name="menu-items-reorder",
    ),
    url(r"^ajax/links/$", views.ajax_menu_links, name="ajax-menu-links"),
]

saleor/dashboard/urls.py
from django.conf.urls import include, url

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .collection.urls import urlpatterns as collection_urls
from .customer.urls import urlpatterns as customer_urls
from .discount.urls import urlpatterns as discount_urls
from .menu.urls import urlpatterns as menu_urls
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls
from .shipping.urls import urlpatterns as shipping_urls
from .sites.urls import urlpatterns as site_urls
from .staff.urls import urlpatterns as staff_urls
from .taxes.urls import urlpatterns as taxes_urls

urlpatterns = [
    url(r"^$", core_views.index, name="index"),
    url(r"^categories/", include(category_urls)),
    url(r"^collections/", include(collection_urls)),
    url(r"^orders/", include(order_urls)),
    url(r"^page/", include(page_urls)),
    url(r"^products/", include(product_urls)),
    url(r"^customers/", include(customer_urls)),
    url(r"^staff/", include(staff_urls)),
    url(r"^discounts/", include(discount_urls)),
    url(r"^settings/", include(site_urls)),
    url(r"^menu/", include(menu_urls)),
    url(r"^shipping/", include(shipping_urls)),
    url(r"^style-guide/", core_views.styleguide, name="styleguide"),
    url(r"^search/", include(search_urls)),
    url(r"^taxes/", include(taxes_urls)),
]

saleor/order/urls.py
from django.conf.urls import url

from ..core import TOKEN_PATTERN
from . import views

urlpatterns = [
    url(r"^%s/$" % (TOKEN_PATTERN,), views.details, name="details"),
    url(r"^%s/payment/$" % (TOKEN_PATTERN,), views.payment, name="payment"),
    url(
        r"^%s/payment/(?P<gateway>[-\w]+)/$" % (TOKEN_PATTERN,),
        views.start_payment,
        name="payment",
    ),
    url(
        r"^%s/cancel-payment/$" % (TOKEN_PATTERN,),
        views.cancel_payment,
        name="cancel-payment",
    ),
    url(
        r"^%s/payment-success/$" % (TOKEN_PATTERN,),
        views.payment_success,
        name="payment-success",
    ),
    url(
        r"^%s/checkout-success/$" % (TOKEN_PATTERN,),
        views.checkout_success,
        name="checkout-success",
    ),
    url(
        r"^%s/attach/$" % (TOKEN_PATTERN,),
        views.connect_order_with_user,
        name="connect-order-with-user",
    ),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import checkout_urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = "saleor.core.views.handle_404"

non_translatable_urlpatterns = [
    url(r"^dashboard/", include((dashboard_urls, "dashboard"), namespace="dashboard")),
    url(r"^graphql/", csrf_exempt(GraphQLView.as_view(schema=schema)), name="api"),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(r"^i18n/$", set_language, name="set_language"),
    url("", include("social_django.urls", namespace="social")),
]

translatable_urlpatterns = [
    url(r"^", include(core_urls)),
    url(r"^checkout/", include((checkout_urls, "checkout"), namespace="checkout")),
    url(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(r"^order/", include((order_urls, "order"), namespace="order")),
    url(r"^page/", include((page_urls, "page"), namespace="page")),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    url(r"^account/", include((account_urls, "account"), namespace="account")),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(r"^search/", include((search_urls, "search"), namespace="search")),
]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(*translatable_urlpatterns)

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        """The debug toolbar was not installed. Ignore the error.
        settings.py should already have warned the user about it."""
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

    urlpatterns += [
        # static files (images, css, javascript, etc.)
        url(r"^static/(?P<path>.*)$", serve)
    ] + static("/media/", document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [url(r"^silk/", include("silk.urls", namespace="silk"))]

saleor/order/models.py
from decimal import Decimal
from operator import attrgetter
from uuid import uuid4

from django.conf import settings
from django.contrib.postgres.fields import JSONField
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import F, Max, Sum
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import pgettext_lazy
from django_measurement.models import MeasurementField
from django_prices.models import MoneyField, TaxedMoneyField
from measurement.measures import Weight
from prices import Money

from ..account.models import Address
from ..core.taxes import zero_money, zero_taxed_money
from ..core.utils.json_serializer import CustomJsonEncoder
from ..core.weight import WeightUnits, zero_weight
from ..discount.models import Voucher
from ..giftcard.models import GiftCard
from ..payment import ChargeStatus, TransactionKind
from ..shipping.models import ShippingMethod
from . import FulfillmentStatus, OrderEvents, OrderStatus


class OrderQueryset(models.QuerySet):
    def confirmed(self):
        """Return non-draft orders."""
        return self.exclude(status=OrderStatus.DRAFT)

    def drafts(self):
        """Return draft orders."""
        return self.filter(status=OrderStatus.DRAFT)

    def ready_to_fulfill(self):
        """Return orders that can be fulfilled.

        Orders ready to fulfill are fully paid but unfulfilled (or partially
        fulfilled).
        """
        statuses = {OrderStatus.UNFULFILLED, OrderStatus.PARTIALLY_FULFILLED}
        qs = self.filter(status__in=statuses, payments__is_active=True)
        qs = qs.annotate(amount_paid=Sum("payments__captured_amount"))
        return qs.filter(total_gross__lte=F("amount_paid"))

    def ready_to_capture(self):
        """Return orders with payments to capture.

        Orders ready to capture are those which are not draft or canceled and
        have a preauthorized payment. The preauthorized payment can not
        already be partially or fully captured.
        """
        qs = self.filter(
            payments__is_active=True, payments__charge_status=ChargeStatus.NOT_CHARGED
        )
        qs = qs.exclude(status={OrderStatus.DRAFT, OrderStatus.CANCELED})
        return qs.distinct()


class Order(models.Model):
    created = models.DateTimeField(default=now, editable=False)
    status = models.CharField(
        max_length=32, default=OrderStatus.UNFULFILLED, choices=OrderStatus.CHOICES
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        related_name="orders",
        on_delete=models.SET_NULL,
    )
    language_code = models.CharField(max_length=35, default=settings.LANGUAGE_CODE)
    tracking_client_id = models.CharField(max_length=36, blank=True, editable=False)
    billing_address = models.ForeignKey(
        Address, related_name="+", editable=False, null=True, on_delete=models.SET_NULL
    )
    shipping_address = models.ForeignKey(
        Address, related_name="+", editable=False, null=True, on_delete=models.SET_NULL
    )
    user_email = models.EmailField(blank=True, default="")
    shipping_method = models.ForeignKey(
        ShippingMethod,
        blank=True,
        null=True,
        related_name="orders",
        on_delete=models.SET_NULL,
    )
    shipping_price_net = MoneyField(
        currency=settings.DEFAULT_CURRENCY,
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        default=0,
        editable=False,
    )
    shipping_price_gross = MoneyField(
        currency=settings.DEFAULT_CURRENCY,
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        default=0,
        editable=False,
    )
    shipping_price = TaxedMoneyField(
        net_field="shipping_price_net", gross_field="shipping_price_gross"
    )
    shipping_method_name = models.CharField(
        max_length=255, null=True, default=None, blank=True, editable=False
    )
    token = models.CharField(max_length=36, unique=True, blank=True)
    # Token of a checkout instance that this order was created from
    checkout_token = models.CharField(max_length=36, blank=True)
    total_net = MoneyField(
        currency=settings.DEFAULT_CURRENCY,
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        default=zero_money,
    )
    total_gross = MoneyField(
        currency=settings.DEFAULT_CURRENCY,
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        default=zero_money,
    )
    total = TaxedMoneyField(net_field="total_net", gross_field="total_gross")
    voucher = models.ForeignKey(
        Voucher, blank=True, null=True, related_name="+", on_delete=models.SET_NULL
    )
    gift_cards = models.ManyToManyField(GiftCard, blank=True, related_name="orders")
    discount_amount = MoneyField(
        currency=settings.DEFAULT_CURRENCY,
        max_digits=settings.DEFAULT_MAX_DIGITS,
        decimal_places=settings.DEFAULT_DECIMAL_PLACES,
        default=zero_money,
    )
    discount_name = models.CharField(max_length=255, default="", blank=True)
    translated_discount_name = models.CharField(max_length=255, default="", blank=True)
    display_gross_prices = models.BooleanField(default=True)
    customer_note = models.TextField(blank=True, default="")
    weight = MeasurementField(
        measurement=Weight, unit_choices=WeightUnits.CHOICES, default=zero_weight
    )
    objects = OrderQueryset.as_manager()

    class Meta:
        ordering = ("-pk",)
        permissions = (
            (
                "manage_orders",
                pgettext_lazy("Permission description", "Manage orders."),
            ),
        )

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = str(uuid4())
        return super().save(*args, **kwargs)

    def is_fully_paid(self):
        total_paid = self._total_paid()
        return total_paid.gross >= self.total.gross

    def is_partly_paid(self):
        total_paid = self._total_paid()
        return total_paid.gross.amount > 0

    def get_customer_email(self):
        return self.user.email if self.user else self.user_email

    def _total_paid(self):
        # Get total paid amount from partially charged,
        # fully charged and partially refunded payments
        payments = self.payments.filter(
            charge_status__in=[
                ChargeStatus.PARTIALLY_CHARGED,
                ChargeStatus.FULLY_CHARGED,
                ChargeStatus.PARTIALLY_REFUNDED,
            ]
        )
        total_captured = [payment.get_captured_amount() for payment in payments]
        total_paid = sum(total_captured, zero_taxed_money())
        return total_paid

    def _index_billing_phone(self):
        return self.billing_address.phone

    def _index_shipping_phone(self):
        return self.shipping_address.phone

    def __iter__(self):
        return iter(self.lines.all())

    def __repr__(self):
        return "<Order #%r>" % (self.id,)

    def __str__(self):
        return "#%d" % (self.id,)

    def get_absolute_url(self):
        return reverse("order:details", kwargs={"token": self.token})

    def get_last_payment(self):
        return max(self.payments.all(), default=None, key=attrgetter("pk"))

    def get_payment_status(self):
        last_payment = self.get_last_payment()
        if last_payment:
            return last_payment.charge_status
        return ChargeStatus.NOT_CHARGED

    def get_payment_status_display(self):
        last_payment = self.get_last_payment()
        if last_payment:
            return last_payment.get_charge_status_display()
        return dict(ChargeStatus.CHOICES).get(ChargeStatus.NOT_CHARGED)

    def is_pre_authorized(self):
        return (
            self.payments.filter(
                is_active=True, transactions__kind=TransactionKind.AUTH
            )
            .filter(transactions__is_success=True)
            .exists()
        )

    @property
    def quantity_fulfilled(self):
        return sum([line.quantity_fulfilled for line in self])

    def is_shipping_required(self):
        return any(line.is_shipping_required for line in self)

    def get_subtotal(self):
        subtotal_iterator = (line.get_total() for line in self)
        return sum(subtotal_iterator, zero_taxed_money())

    def get_total_quantity(self):
        return sum([line.quantity for line in self])

    def is_draft(self):
        return self.status == OrderStatus.DRAFT

    def is_open(self):
        statuses = {OrderStatus.UNFULFILLED, OrderStatus.PARTIALLY_FULFILLED}
        return self.status in statuses

    def can_cancel(self):
        return self.status not in {OrderStatus.CANCELED, OrderStatus.DRAFT}

    def can_capture(self, payment=None):
        if not payment:
            payment = self.get_last_payment()
        if not payment:
            return False
        order_status_ok = self.status not in {OrderStatus.DRAFT, OrderStatus.CANCELED}
        return payment.can_capture() and order_status_ok

    def can_charge(self, payment=None):
        if not payment:
            payment = self.get_last_payment()
        if not payment:
            return False
        order_status_ok = self.status not in {OrderStatus.DRAFT, OrderStatus.CANCELED}
        return payment.can_charge() and order_status_ok

    def can_void(self, payment=None):
        if not payment:
            payment = self.get_last_payment()
        if not payment:
            return False
        return payment.can_void()

    def can_refund(self, payment=None):
        if not payment:
            payment = self.get_last_payment()
        if not payment:
            return False
        return payment.can_refund()

    def can_mark_as_paid(self):
        return len(self.payments.all()) == 0

saleor/dashboard/search/forms.py
from ...search.backends import picker
from ...search.forms import SearchForm


class DashboardSearchForm(SearchForm):
    def search(self):
        query = self.cleaned_data["q"]
        search = picker.pick_dashboard_backend()
        return search(query)

templates/dashboard/order/address_form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}
  {% trans "Edit address" context "" %} - {% trans "Orders" context "Dashboard orders list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-orders{% endblock %}

{% block menu_orders_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:orders" as url %}
  {% include "dashboard/includes/_back_link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:orders" %}">
        {% trans "Orders" context "Dashboard orders list" %}
      </a>
    </li>
    <li class="hide-on-med-and-down">
      <a href="{% url "dashboard:order-details" order_pk=order.pk %}">
        #{{ order.pk }}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:order-details" order_pk=order.pk %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% if address_type == "shipping" %}
          {% trans "Shipping address" context "" %}
        {% else %}
          {% trans "Billing address" context "" %}
        {% endif %}
      </span>
    </li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 m9">
      <div class="card">
        <form method="post" novalidate>
          <div class="card-content">
            {% csrf_token %}
            <div class="row">
              {{ form|materializecss }}
            </div>
          </div>
          <div class="card-action right-align">
            <a href="{% url "dashboard:order-details" order_pk=order.pk %}" class="btn-flat waves-effect">
              {% trans "Cancel" context "Dashboard cancel action" %}
            </a>
            <button type="submit" class="btn waves-effect">
              {% trans "Update" context "Dashboard update action" %}
            </button>
          </div>
        </form>
      </div>
    </div>
    <div class="col s12 m3"></div>
  </div>
{% endblock %}

templates/dashboard/order/fulfillment.html
{% extends "dashboard/base.html" %}
{% load babel %}
{% load dashboard %}
{% load i18n %}
{% load i18n_address_tags %}
{% load materializecss %}
{% load static %}
{% load status %}

{% block title %}
  {% trans "Fulfill" context "Dashboard order fulfillment" %} {{ order }} - {% trans "Orders" context "Dashboard orders list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-orders{% endblock %}

{% block menu_orders_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:orders" as url %}
  {% include "dashboard/includes/_back_link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:orders" %}">
        {% trans "Orders" context "Dashboard orders list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:orders" %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      <a href="{% url 'dashboard:order-details' order_pk=order.pk %}" class="breadcrumbs--ellipsed-item">
        {{ order }}
      </a>
    </li>
    <li>
      <span>
        {% trans "Fulfill" context "Dashboard order fulfillment" %}
      </span>
    </li>
  </ul>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col s12 l8">
    <form role="form" class="card" method="post" novalidate>
    {% csrf_token %}
    {{ formset.management_form }}
      <div class="card shipment-table">
        <div class="data-table-header">
          <div class="data-table-title">
            <h5>
              {% trans "Fulfill order" context "Fulfill order title" %}
            </h5>
          </div>
        </div>
        <div class="data-table-container">
          <table class="bordered highlight responsive data-table">
            <thead>
              <tr>
                <th class="wide">
                  {% trans "Item" context "Modal remove order line table header" %}
                </th>
                <th class="right-align">
                  {% trans "Quantity" context "Modal remove order line table header" %}
                </th>
              </tr>
            </thead>
            <tbody>
              {% for line in unfulfilled_lines %}
                <tr>
                  <td>
                    {% if line.variant %}
                      <a href="{% url 'dashboard:variant-details' product_pk=line.variant.product.pk variant_pk=line.variant.pk %}">{{ line.product_name }}</a>
                    {% else %}
                      {{ line.product_name }}
                    {% endif %}
                    <br>
                    <span class="grey-text">
                      {% blocktrans trimmed with sku=line.product_sku context "Order table text" %}
                        SKU: {{ sku }}
                      {% endblocktrans %}
                    </span>
                  </td>
                  <td class="right-align fulfillment-quantity">
                    {% get_formset_form formset forloop.counter0 as line_form %}
                    <div class="fulfillment-quantity-input">
                      <input id="{{ line_form.order_line.auto_id }}"
                             type="hidden"
                             name="{{ line_form.order_line.html_name }}"
                             required="{{ line_form.order_line.field.required }}"
                             value="{{ line_form.order_line.value }}">
                      <input id="{{ line_form.quantity.auto_id }}"
                             max="{{ line.quantity_unfulfilled }}"
                             min="0"
                             name="{{ line_form.quantity.html_name }}"
                             required="{{ line_form.quantity.field.required }}"
                             type="number"
                             value="{{ line_form.quantity.value }}">
                      {% blocktrans trimmed with quantity_unfulfilled=line.quantity_unfulfilled context "Fulfill order table quantity unfulfilled" %}
                        of {{ quantity_unfulfilled }}
                      {% endblocktrans %}
                    </div>
                    <label for="{{ line_form.quantity.auto_id }}">
                      {% for error in line_form.quantity.errors %}
                        <p class="help-block materialize-red-text">{{ error }}</p>
                      {% endfor %}
                      {% for error in formset.non_form_errors %}
                        <p class="help-block materialize-red-text">{{ error }}</p>
                      {% endfor %}
                      {% if line_form.quantity.help_text %}
                        <p class="help-block">
                          {{ line_form.quantity.field.help_text|safe }}
                        </p>
                      {% endif %}
                    </label>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="data-table-content">
          {{ form.tracking_number|materializecss }}
          {% if form.send_mail %}
            {{ form.send_mail|materializecss }}
          {% endif %}
        </div>
        <div class="data-table-action right-align">
          <a href="{% url 'dashboard:order-details' order.pk %}" class="btn-flat waves-effect">
            {% trans "Cancel" context "Dashboard cancel action" %}
          </a>
          <button type="submit" class="btn waves-effect">
            {% trans "Fulfill" context "Dashboard update action" %}
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/dashboard/order/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load price from taxed_prices %}
{% load prices_i18n %}
{% load status %}
{% load utils %}
{% load static %}

{% block title %}{% trans "Orders" context "Dashboard orders list" %} - {{ block.super }}{% endblock %}

{% block body_class %}body-orders{% endblock %}

{% block menu_orders_class %}active{% endblock %}

{% block header_extra %}
  <div class="btn-fab-fixed">
    <form method="POST" action="{% url "dashboard:order-create" %}">
    {% csrf_token %}
      <label class="btn-fab-default waves-effect waves-light svg-submit-btn" title="{% trans "Add order" context "Order list add button text" %}">
        <input type="submit" />
        <svg data-src="{% static "dashboard/images/add.svg" %}" />
      </label>
    </form>
  </div>
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs">
    <li class="visible-s">{% trans "Orders" context "Dashboard orders list" %}</li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l9">
      {% if orders %}
        <div class="card">
          <div class="data-table-container">
            <table class="bordered highlight responsive data-table last-right-align">
              <thead>
                <tr>
                  {% sorting_header 'pk' '#' %}

                  {% trans "Placed on" context "Orders table header" as label %}
                  {% sorting_header 'created' label %}

                  {% trans "Customer" context "Orders table header" as label %}
                  {% sorting_header 'email' label %}

                  {% trans "Payment status" context "Orders table header" as label %}
                  {% sorting_header 'payment_status' label %}

                  {% trans "Order status" context "Orders table header" as label %}
                  {% sorting_header 'order_status' label %}

                  {% trans "Total" context "Orders table header" as label %}
                  {% sorting_header 'total' label %}
                </tr>
              </thead>
              <tbody>
                {% for order in orders %}
                  <tr data-action-go="{% url 'dashboard:order-details' order_pk=order.pk %}">
                    <td>
                      #{{ order.id }}
                    </td>
                    <td>
                      {{ order.created }}
                    </td>
                    {% trans "Guest" context "Anonymous user account value" as guest %}
                    <td>
                      {{ order.user|default:guest }}
                    </td>
                    <td>
                      {% render_status order.get_payment_status order.get_payment_status_display %}
                    </td>
                    <td>
                      {% render_order_status order.status order.get_status_display %}
                    </td>
                    <td class="right-align">
                      {% price order.total.gross %}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="row">
          {% paginate orders %}
        </div>
      {% else %}
        {% if is_empty %}
          {% include 'dashboard/order/zero_page.html' %}
        {% else %}
          <div class="col s12">
            <div class="not-found">
              <p class="grey-text">
                {% trans "No orders found." context "Empty order list message" %}
              </p>
            </div>
          </div>
        {% endif %}
      {% endif %}
    </div>
    <div class="col s12 l3" id="filters">
      {% if not is_empty %}{% filters filter_set %}{% endif %}
    </div>
  </div>
{% endblock %}

templates/dashboard/order/zero_page.html
{% extends 'dashboard/base_zero_page.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "No orders found." %}{% endblock %}
{% block content %}
  {% static "dashboard/images/add.svg" as img_path %}
  {% blocktrans %}
    Orders will appear here after customers complete the checkout.
  {% endblocktrans %}
{% endblock %}