saleor/dashboard/customer/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.customer_list, name="customers"),
    url(r"^create/$", views.customer_create, name="customer-create"),
    url(r"^(?P<pk>[0-9]+)/$", views.customer_details, name="customer-details"),
    url(r"^(?P<pk>[0-9]+)/update/$", views.customer_edit, name="customer-update"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.customer_delete, name="customer-delete"),
    url(r"^ajax/users/$", views.ajax_users_list, name="ajax-users-list"),
    url(
        r"^(?P<customer_pk>[0-9]+)/add-note/$",
        views.customer_add_note,
        name="customer-add-note",
    ),
]

saleor/dashboard/menu/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.menu_list, name="menu-list"),
    url(r"^add/$", views.menu_create, name="menu-add"),
    url(r"^(?P<pk>[0-9]+)/edit/$", views.menu_edit, name="menu-edit"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.menu_delete, name="menu-delete"),
    url(r"^(?P<pk>[0-9]+)/$", views.menu_details, name="menu-details"),
    url(r"^(?P<menu_pk>[0-9]+)/add/$", views.menu_item_create, name="menu-item-add"),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/add/$",
        views.menu_item_create,
        name="menu-item-add",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/edit/$",
        views.menu_item_edit,
        name="menu-item-edit",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/delete/$",
        views.menu_item_delete,
        name="menu-item-delete",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/$",
        views.menu_item_details,
        name="menu-item-details",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/items/reorder/$",
        views.ajax_reorder_menu_items,
        name="menu-items-reorder",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/items/reorder/$",
        views.ajax_reorder_menu_items,
        name="menu-items-reorder",
    ),
    url(r"^ajax/links/$", views.ajax_menu_links, name="ajax-menu-links"),
]

saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.order_list, name="orders"),
    url(r"^add/$", views.order_create, name="order-create"),
    url(
        r"^(?P<order_pk>\d+)/create/$",
        views.create_order_from_draft,
        name="create-order-from-draft",
    ),
    url(r"^(?P<order_pk>\d+)/$", views.order_details, name="order-details"),
    url(r"^(?P<order_pk>\d+)/add-note/$", views.order_add_note, name="order-add-note"),
    url(r"^(?P<order_pk>\d+)/cancel/$", views.cancel_order, name="order-cancel"),
    url(
        r"^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$",
        views.order_address,
        name="address-edit",
    ),
    url(
        r"^(?P<order_pk>\d+)/edit-customer/$",
        views.order_customer_edit,
        name="order-customer-edit",
    ),
    url(
        r"^(?P<order_pk>\d+)/remove-customer/$",
        views.order_customer_remove,
        name="order-customer-remove",
    ),
    url(
        r"^(?P<order_pk>\d+)/edit-shipping/$",
        views.order_shipping_edit,
        name="order-shipping-edit",
    ),
    url(
        r"^(?P<order_pk>\d+)/remove-shipping/$",
        views.order_shipping_remove,
        name="order-shipping-remove",
    ),
    url(
        r"^(?P<order_pk>\d+)/edit-discount/$",
        views.order_discount_edit,
        name="order-discount-edit",
    ),
    url(
        r"^(?P<order_pk>\d+)/edit-voucher/$",
        views.order_voucher_edit,
        name="order-voucher-edit",
    ),
    url(
        r"^(?P<order_pk>\d+)/remove-voucher/$",
        views.order_voucher_remove,
        name="order-voucher-remove",
    ),
    url(
        r"^(?P<order_pk>\d+)/delete/$",
        views.remove_draft_order,
        name="draft-order-delete",
    ),
    url(
        r"^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$",
        views.capture_payment,
        name="capture-payment",
    ),
    url(
        r"^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/void/$",
        views.void_payment,
        name="void-payment",
    ),
    url(
        r"^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$",
        views.refund_payment,
        name="refund-payment",
    ),
    url(
        r"^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$",
        views.orderline_change_quantity,
        name="orderline-change-quantity",
    ),
    url(
        r"^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$",
        views.orderline_cancel,
        name="orderline-cancel",
    ),
    url(
        r"^(?P<order_pk>\d+)/add-variant/$",
        views.add_variant_to_order,
        name="add-variant-to-order",
    ),
    url(
        r"^(?P<order_pk>\d+)/fulfill/$",
        views.fulfill_order_lines,
        name="fulfill-order-lines",
    ),
    url(
        r"^(?P<order_pk>\d+)/fulfillment/(?P<fulfillment_pk>\d+)/cancel/$",
        views.cancel_fulfillment,
        name="fulfillment-cancel",
    ),
    url(
        r"^(?P<order_pk>\d+)/fulfillment/(?P<fulfillment_pk>\d+)/tracking/$",
        views.change_fulfillment_tracking,
        name="fulfillment-change-tracking",
    ),
    url(
        r"^(?P<order_pk>\d+)/fulfillment/(?P<fulfillment_pk>\d+)/packing-slips/$",  # noqa
        views.fulfillment_packing_slips,
        name="fulfillment-packing-slips",
    ),
    url(r"^(?P<order_pk>\d+)/invoice/$", views.order_invoice, name="order-invoice"),
    url(
        r"^(?P<order_pk>\d+)/mark-as-paid/$",
        views.mark_order_as_paid,
        name="order-mark-as-paid",
    ),
    url(
        r"^(?P<order_pk>\d+)/ajax/shipping-methods/$",
        views.ajax_order_shipping_methods_list,
        name="ajax-order-shipping-methods",
    ),
]

saleor/dashboard/page/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.page_list, name="page-list"),
    url(r"^add/$", views.page_add, name="page-add"),
    url(r"^(?P<pk>[0-9]+)/$", views.page_details, name="page-details"),
    url(r"^(?P<pk>[0-9]+)/update/$", views.page_update, name="page-update"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.page_delete, name="page-delete"),
]

saleor/dashboard/urls.py
from django.conf.urls import include, url

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .collection.urls import urlpatterns as collection_urls
from .customer.urls import urlpatterns as customer_urls
from .discount.urls import urlpatterns as discount_urls
from .menu.urls import urlpatterns as menu_urls
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls
from .shipping.urls import urlpatterns as shipping_urls
from .sites.urls import urlpatterns as site_urls
from .staff.urls import urlpatterns as staff_urls
from .taxes.urls import urlpatterns as taxes_urls

urlpatterns = [
    url(r"^$", core_views.index, name="index"),
    url(r"^categories/", include(category_urls)),
    url(r"^collections/", include(collection_urls)),
    url(r"^orders/", include(order_urls)),
    url(r"^page/", include(page_urls)),
    url(r"^products/", include(product_urls)),
    url(r"^customers/", include(customer_urls)),
    url(r"^staff/", include(staff_urls)),
    url(r"^discounts/", include(discount_urls)),
    url(r"^settings/", include(site_urls)),
    url(r"^menu/", include(menu_urls)),
    url(r"^shipping/", include(shipping_urls)),
    url(r"^style-guide/", core_views.styleguide, name="styleguide"),
    url(r"^search/", include(search_urls)),
    url(r"^taxes/", include(taxes_urls)),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import checkout_urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = "saleor.core.views.handle_404"

non_translatable_urlpatterns = [
    url(r"^dashboard/", include((dashboard_urls, "dashboard"), namespace="dashboard")),
    url(r"^graphql/", csrf_exempt(GraphQLView.as_view(schema=schema)), name="api"),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(r"^i18n/$", set_language, name="set_language"),
    url("", include("social_django.urls", namespace="social")),
]

translatable_urlpatterns = [
    url(r"^", include(core_urls)),
    url(r"^checkout/", include((checkout_urls, "checkout"), namespace="checkout")),
    url(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(r"^order/", include((order_urls, "order"), namespace="order")),
    url(r"^page/", include((page_urls, "page"), namespace="page")),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    url(r"^account/", include((account_urls, "account"), namespace="account")),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(r"^search/", include((search_urls, "search"), namespace="search")),
]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(*translatable_urlpatterns)

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        """The debug toolbar was not installed. Ignore the error.
        settings.py should already have warned the user about it."""
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

    urlpatterns += [
        # static files (images, css, javascript, etc.)
        url(r"^static/(?P<path>.*)$", serve)
    ] + static("/media/", document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [url(r"^silk/", include("silk.urls", namespace="silk"))]

saleor/dashboard/category/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from django.utils.translation import pgettext_lazy
from text_unidecode import unidecode

from ...product.models import Category
from ...product.thumbnails import create_category_background_image_thumbnails
from ..seo.fields import SeoDescriptionField, SeoTitleField


class CategoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.parent_pk = kwargs.pop("parent_pk")
        super().__init__(*args, **kwargs)
        self.fields["seo_description"] = SeoDescriptionField(
            extra_attrs={"data-bind": self["description"].auto_id}
        )
        self.fields["seo_title"] = SeoTitleField(
            extra_attrs={"data-bind": self["name"].auto_id}
        )

    class Meta:
        model = Category
        exclude = ["slug", "description_json"]
        labels = {
            "name": pgettext_lazy("Item name", "Name"),
            "description": pgettext_lazy("Description", "Description"),
            "background_image": pgettext_lazy("Category form", "Background Image"),
            "background_image_alt": pgettext_lazy(
                "Description of a category image", "Image description"
            ),
        }

    def save(self, commit=True):
        self.instance.slug = slugify(unidecode(self.instance.name))

        if self.parent_pk:
            self.instance.parent = get_object_or_404(Category, pk=self.parent_pk)

        instance = super().save(commit=commit)

        if instance.pk and "background_image" in self.changed_data:
            create_category_background_image_thumbnails.delay(instance.pk)

        return instance

saleor/dashboard/category/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...menu.utils import get_menus_that_need_update, update_menus
from ...product.models import Category
from ..views import staff_member_required
from .filters import CategoryFilter
from .forms import CategoryForm


@staff_member_required
@permission_required("product.manage_products")
def category_list(request):
    categories = Category.tree.root_nodes().order_by("name")
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "categories": categories,
        "filter_set": category_filter,
        "is_empty": not category_filter.queryset.exists(),
    }
    return TemplateResponse(request, "dashboard/category/list.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def category_create(request, root_pk=None):
    path = None
    category = Category()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(request.POST or None, request.FILES or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(
            request, pgettext_lazy("Dashboard message", "Added category %s") % category
        )
        if root_pk:
            return redirect("dashboard:category-details", pk=root_pk)
        return redirect("dashboard:category-list")
    ctx = {"category": category, "form": form, "path": path}
    return TemplateResponse(request, "dashboard/category/form.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def category_edit(request, root_pk=None):
    path = None
    category = get_object_or_404(Category, pk=root_pk)
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(
        request.POST or None,
        request.FILES or None,
        instance=category,
        parent_pk=category.parent_id,
    )
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy("Dashboard message", "Updated category %s") % category,
        )
        if root_pk:
            return redirect("dashboard:category-details", pk=root_pk)
        return redirect("dashboard:category-list")
    elif form.errors:
        status = 400
    ctx = {"category": category, "form": form, "status": status, "path": path}
    template = "dashboard/category/form.html"
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required("product.manage_products")
def category_details(request, pk):
    root = get_object_or_404(Category, pk=pk)
    path = root.get_ancestors(include_self=True) if root else []
    categories = root.get_children().order_by("name")
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "categories": categories,
        "path": path,
        "root": root,
        "filter_set": category_filter,
        "is_empty": not category_filter.queryset.exists(),
    }
    return TemplateResponse(request, "dashboard/category/detail.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        descendants = category.get_descendants()
        menus = get_menus_that_need_update(categories=descendants)
        category.delete()
        if menus:
            update_menus(menus)
        messages.success(
            request,
            pgettext_lazy("Dashboard message", "Removed category %s") % category,
        )
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {
                    "redirectUrl": reverse(
                        "dashboard:category-details", kwargs={"pk": root_pk}
                    )
                }
                return JsonResponse(response)
            return redirect("dashboard:category-details", pk=root_pk)
        else:
            if request.is_ajax():
                response = {"redirectUrl": reverse("dashboard:category-list")}
                return JsonResponse(response)
            return redirect("dashboard:category-list")
    ctx = {
        "category": category,
        "descendants": list(category.get_descendants()),
        "products_count": len(category.products.all()),
    }
    return TemplateResponse(
        request, "dashboard/category/modal/confirm_delete.html", ctx
    )

templates/dashboard/customer/detail.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load price from taxed_prices %}
{% load static %}
{% load status %}

{% block title %}
  {{ customer }} - {% trans "Customers" context "Dashboard customers list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-customers{% endblock %}

{% block menu_customers_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:customers" as url %}
  {% include "dashboard/includes/_back_link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:customers" %}">
        {% trans "Customers" context "Dashboard customers list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:customers" %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      <span class="breadcrumbs--elipsed-item">{{ customer }}</span>
    </li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12 l8">
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            {{ customer.get_full_name }}
          </span>
          {% if customer.get_full_name != customer.email %}
            <p>
              {{ customer.email }}
            </p>
          {% endif %}
          <div class="row">
            {% if customer.date_joined %}
              <div class="col s12 m4 l12">
                <h4>
                  {% trans "Date joined" context "Customer field" %}
                </h4>
                <p>
                  {{ customer.date_joined }}
                </p>
              </div>
            {% endif %}
          </div>
          {% if customer.note %}
            <div class="row">
              <div class="col s12 m4 l12">
                <h4>
                  {% trans "Note" context "Customer field" %}
                </h4>
                <p>
                  {{ customer.note }}
                </p>
              </div>
            </div>
          {% endif %}
        </div>
        <div class="card-action">
          <a href="{% url 'dashboard:customer-update' customer.pk %}" class="btn-flat waves-effect">
            {% trans "Edit customer" context "Customer action" %}
          </a>
          <a href="#base-modal" data-href="{% url 'dashboard:customer-delete' pk=customer.pk %}" class="modal-trigger-custom btn-flat waves-effect">
            {% trans "Remove customer" context "Customer action" %}
          </a>
          {% if perms.account.impersonate_users %}
            <a href="{% url 'impersonate-start' uid=customer.pk %}" class="btn-flat waves-effect">
              {% trans 'Impersonate customer' context 'Customer impersonate action' %}
            </a>
          {% endif %}
        </div>
      </div>

      <div class="card">
        <div class="data-table-header{% if not customer_orders %} data-table-header--no-data{% endif %}">
          <h5 class="data-table-title {% if not customer_orders %} data-table-title--no-data{% endif %}">
            {% trans "Recent orders" context "Customer recent orders table title" %}
          </h5>
        </div>
        {% if customer_orders %}
          <div class="data-table-container">
            <table class="bordered highlight responsive data-table">
              <thead>
                <tr>
                  <th>
                    {% trans "Number" context "Customer orders table header" %}
                  </th>
                  <th>
                    {% trans "Placed on" context "Customer orders table header" %}
                  </th>
                  <th>
                    {% trans "Order status" context "Customer orders table header" %}
                  </th>
                  <th class="right-align">
                    {% trans "Total" context "Customer orders table header" %}
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for order in customer_orders %}
                  <tr data-action-go="{% if perms.order.manage_orders %}{% url 'dashboard:order-details' order_pk=order.pk %}{% endif %}">
                    <td>
                      {{ order }}
                    </td>
                    <td>
                      {{ order.created }}
                    </td>
                    <td>
                      {% render_order_status order.status order.get_status_display %}
                    </td>
                    <td class="right-align">
                      {% price order.total.gross %}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        {% else %}
          <div class="card-content card-content--no-data">
            <p>
              {% trans "No orders found." context "Empty customer orders table message" %}
            </p>
          </div>
        {% endif %}
      </div>

      <div class="card">
        <div class="card-content">
          <span class="card-title">
            {% trans "Customer notes" context "Customer notes card title" %}
          </span>
          {% if notes %}
            <ul class="list">
              {% for note in notes %}
                <li class="list-item list-item--spaced">
                  <small class="list-item-author">{{ note.user }} - {{ note.date }}</small>
                  <p>{{ note.content }}</p>
                </li>
              {% endfor %}
            </ul>
          {% else %}
            <div>
              {% trans "There are no notes associated with this customer" context "Customer without notes message" %}
            </div>
          {% endif %}
        </div>
        <div class="card-action">
          <a data-href="{% url "dashboard:customer-add-note" customer_pk=customer.pk %}" class="modal-trigger-custom btn-flat waves-effect" href="#base-modal">
            {% trans "Add note" context "Customer notes card action" %}
          </a>
        </div>
      </div>
    </div>


    <div class="col s12 l4">
       <div class="row">
        <div class="col s12 m6 p6 l12">
          <div class="card equal-height-on-med">
            <div class="card-content">
              <span class="card-title black-text">
                {% trans "Default shipping address" context "Customer default shipping address card title" %}
              </span>
              {% if customer.default_shipping_address %}
                {% with customer.default_shipping_address as address %}
                  {% include 'dashboard/includes/_address.html' with address=address only %}
                {% endwith %}
              {% else %}
                <div>{% trans "No default shipping address." context "Customer without default shipping address message" %}</div>
              {% endif %}
              <svg data-src="{% static "dashboard/images/email.svg" %}" width="14" height="14" />
              <a href="mailto:{{ customer.email }}">
                {{ customer.email }}
              </a>
            </div>
          </div>
        </div>
        <div class="col s12 m6 p6 l12">
          <div class="card equal-height-on-med">
            <div class="card-content">
              <span class="card-title black-text">
                {% trans "Default billing address" context "Customer default billing address card title" %}
              </span>
              {% if customer.default_billing_address %}
                {% with customer.default_billing_address as address %}
                  {% include 'dashboard/includes/_address.html' with address=address only %}
                {% endwith %}
              {% else %}
                <div>
                  {% trans "No default billing address." context "Customer without default billing address message" %}
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/customer/form.html
{% extends "dashboard/base.html" %}
{% load materializecss %}
{% load i18n %}
{% load static %}

{% block title %}
  {% if customer.pk %}
    {{ customer }}
  {% else %}
    {% trans "Add new customer" context "Dashboard add customer" %}
  {% endif %}
     - {% trans "Customer" context "Dashboard customer" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-customers{% endblock %}

{% block menu_customers_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:customers" as url %}
  {% include "dashboard/includes/_back-link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:customers" %}">
        {% trans "Customers" context "Dashboard customers list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:customers" %}">
        <svg data-src="{% static "dashboard/images/arrow_left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li><span class="breadcrumbs--elipsed-item">{% if customer.pk %}{{ customer }}{% else %}{% trans 'Add customer' context 'Dashboard add customer action' %}{% endif %}</span></li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l8">
      {% if form %}
        <form class="card" method="post">
          <div class="card-content">
            <span class="card-title">
              {% trans 'Customer details' context 'Customer details header' %}
            </span>
            <div class="data">
              {% csrf_token %}
              <div class="row">
                {{ form|materializecss }}
              </div>
            </div>
          </div>
          <div class="card-action right-align">
            {% if customer.pk %}
              <a href="{% url 'dashboard:customer-details' pk=customer.pk %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans 'Update' context 'Dashboard update action' %}
              </button>
            {% else %}
              <a href="{% url 'dashboard:customers' %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans 'Add' context 'Dashboard add action' %}
              </button>
            {% endif %}
          </div>
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/dashboard/customer/zero_page.html
{% extends 'dashboard/base_zero_page.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "No customers found." %}{% endblock %}
{% block content %}
  {% static "dashboard/images/add.svg" as img_path %}
  {% blocktrans %}
    Customer accounts will appear here once users register in the shop.
  {% endblocktrans %}
{% endblock %}